### PR TITLE
feat: implement mock for importLibrary

### LINKED ISSUE #468: Core: importLibrary method is missing in provided google object
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version
3. Library version and other environment information

 "@googlemaps/jest-mocks": "^2.19.1",
 Maps Javascript API v3.53

#### Steps to reproduce

  1. Load the Google Map by using [Dynamic Library Import](https://developers.google.com/maps/documentation/javascript/load-maps-js-api#dynamic-library-import)
  2. Install "@googlemaps/jest-mocks": "^2.19.1"
  3. Initialize code in jest config file
  4. Run jest tests

#### Stack trace
```
TypeError: google.maps.importLibrary is not a function
```

**Actual Behavior:** 
The `@googlemaps/jest-mocks` package doesn't implement the interface of google object according to `@googlemaps/js-types@^3.52.5` https://github.com/googlemaps/js-types/blob/cd43a417bbc7b713768b0448a35855115f90f494/index.d.ts#L6980 . `importLibrary` is missing at the latest version of `@googlemaps/jest-mocks` https://github.com/googlemaps/js-jest-mocks/blob/main/src/index.ts#L67

**Expected Behavior**: 
The `@googlemaps/jest-mocks` package implement `importLibrary` method according to `@googlemaps/js-types@^3.52.5`

### PR DESCRIPTION
**Pull request by usefulthink**
Implemented a mock for importLibrary that returns the correct collection of api-objects in their mocked versions.

closes #468

### CODE REVIEW

**Comment by douar** [comment]
Hi @usefulthink!

I'm using the loader.importLibrary from @googlemaps/js-api-loader:
Screenshot 2024-06-12 at 12 06 31 PM

Does the mock importLibrary allow us to simulate an error to trigger catch block? 

Any information would be much appreciated, thank you!

**Comment by usefulthink** [comment]
In this case you should probably use [`jest.mock()`](https://jestjs.io/docs/mock-functions#mocking-partials) to to mock out the actual implementation of the `@googlemaps/js-api-loader` module and replace the functions involved in the code you're testing. Then you can fully control what you want the loader to do in order to test how your application responds instead of testing with the api-loader in the loop which can be quite error-prone.

I've done something like that here, and it greatly simplified the whole testing setup: https://github.com/googlemaps/react-wrapper/blob/4667a308533f54591d89057775eb6ec8c4e73b35/src/index.test.tsx

**Comment by douar** [comment]
I will give that a try! Thank you!

**Comment by usefulthink** [comment]
@douar One more thing I just thought about - if you need the actual return values of `importLibrary` in your tests, you can do that as well. Here's an example for that: https://github.com/visgl/react-google-maps/blob/main/src/components/__tests__/info-window.test.tsx#L24-L36 (in that test, the `useMapsLibraryMock` is roughly equivalent to the `Loader.importLibrary` function).

**Comment by douar** [comment]
> @douar One more thing I just thought about - if you need the actual return values of `importLibrary` in your tests, you can do that as well. Here's an example for that: https://github.com/visgl/react-google-maps/blob/main/src/components/__tests__/info-window.test.tsx#L24-L36 (in that test, the `useMapsLibraryMock` is roughly equivalent to the `Loader.importLibrary` function).

That is definitely helpful! Thank you for the references and resources :smile:

**Pull request merged**
